/**
 * GET/POST /api/v1/cron/billing/auto-generate — Scheduled auto-generation for billing.
 * Automatically generates bills for open periods that have reached the 5th day of the next month.
 *
 * Security: Guarded by BILLING_CRON_SECRET or CRON_SECRET if configured.
 * Query param: ?institutionId=<id> (optional)
 */
import { NextRequest, NextResponse } from "next/server";
import { autoGenerateDuePeriods } from "@/lib/domain/billing";
import { sweepOutbox } from "@/lib/outbox";

export const dynamic = "force-dynamic";

function authorizeCron(req: NextRequest): boolean {
  const secret = process.env.BILLING_CRON_SECRET || process.env.CRON_SECRET;
  // If no secret configured in development, allow execution
  if (!secret) return true;

  const authHeader = req.headers.get("authorization");
  const cronHeader = req.headers.get("x-cron-secret");
  const bearer = authHeader?.startsWith("Bearer ") ? authHeader.slice(7) : null;

  return bearer === secret || cronHeader === secret;
}

async function handleCron(req: NextRequest) {
  if (!authorizeCron(req)) {
    return NextResponse.json(
      { ok: false, error: { code: "UNAUTHORIZED", message: "Invalid cron authorization." } },
      { status: 401 }
    );
  }

  const url = new URL(req.url);
  const institutionId = url.searchParams.get("institutionId") ?? undefined;

  try {
    const result = await autoGenerateDuePeriods(institutionId);

    if (result.generated.length > 0) {
      sweepOutbox(100).catch(() => {});
    }

    return NextResponse.json({
      ok: true,
      data: {
        ...result,
        totalGenerated: result.generated.length,
        totalSkipped: result.skipped.length,
        timestamp: new Date().toISOString(),
      },
    });
  } catch (err: any) {
    return NextResponse.json(
      { ok: false, error: { code: "INTERNAL", message: err?.message ?? "Auto-generation failed." } },
      { status: 500 }
    );
  }
}

export async function GET(req: NextRequest) {
  return handleCron(req);
}

export async function POST(req: NextRequest) {
  return handleCron(req);
}
