/**
 * GET /api/v1/admin/billing/periods — billing period list (auth ADMIN).
 * Opportunistically runs auto-generation for due periods (5th of next month),
 * ensures the current month's OPEN period exists (never future months),
 * and returns all periods with bill counts + status.
 */
import { route } from "@/lib/auth/guard";
import { getInstitution } from "@/lib/institution";
import { autoGenerateDuePeriods, getOrCreateOpenPeriod, listPeriods } from "@/lib/domain/billing";
import { sweepOutbox } from "@/lib/outbox";

export const dynamic = "force-dynamic";

export const GET = route({ auth: "ADMIN" }, async (ctx) => {
  const inst = await getInstitution(ctx.institutionId);
  const tz = inst?.timezone ?? "Asia/Kolkata";

  // Opportunistically trigger auto-generation for any due periods (5th day of next month)
  const autoGenResult = await autoGenerateDuePeriods(ctx.institutionId).catch(() => ({
    generated: [],
    skipped: [],
  }));
  if (autoGenResult.generated.length > 0) {
    sweepOutbox(100).catch(() => {});
  }

  const current = await getOrCreateOpenPeriod(ctx.institutionId, tz);
  const periods = await listPeriods(ctx.institutionId);

  return {
    data: periods,
    meta: {
      currentPeriodId: current.id,
      currentPeriod: { id: current.id, year: current.year, month: current.month, status: current.status },
      autoGeneratedCount: autoGenResult.generated.length,
    },
  };
});
