import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";

function source(path: string): string {
  return readFileSync(new URL(`../../${path}`, import.meta.url), "utf8");
}

describe("live billing preview and publication source contracts", () => {
  test("reading billing periods can never auto-publish bills", () => {
    const periods = source("src/app/api/v1/admin/billing/periods/route.ts");
    expect(periods).not.toContain("autoGenerateDuePeriods");
    expect(periods).not.toContain("sweepOutbox");
    expect(periods).toContain("automaticPublishing: false");
  });

  test("legacy billing cron is non-mutating compatibility diagnostics", () => {
    const cron = source("src/app/api/v1/cron/billing/auto-generate/route.ts");
    expect(cron).not.toContain("autoGenerateDuePeriods");
    expect(cron).not.toContain("generateBilling");
    expect(cron).not.toContain("sweepOutbox");
    expect(cron).toContain("automaticPublishing: false");
    expect(cron).toContain("Admin publishes");
  });

  test("manual publish API enforces publication timing before immutable generation", () => {
    const route = source("src/app/api/v1/admin/billing/periods/[id]/generate/route.ts");
    const guardAt = route.indexOf("assertBillingPublicationWindowOpen(ctx.params.id)");
    const generateAt = route.indexOf("generateBilling(ctx.params.id");
    expect(guardAt).toBeGreaterThan(0);
    expect(generateAt).toBeGreaterThan(guardAt);
  });

  test("readiness explicitly exposes LIVE/WAITING/READY publication gating", () => {
    const route = source("src/app/api/v1/admin/billing/periods/[id]/readiness/route.ts");
    expect(route).toContain('key: "billing_month_closed"');
    expect(route).toContain('key: "publish_window_open"');
    expect(route).toContain("publication.state === \"LIVE\"");
    expect(route).toContain("publication.state === \"WAITING\"");
    expect(route).toContain("automaticPublishing: false");
    expect(route).toContain("const ready = checks.every((check) => check.pass)");
  });

  test("successful mutations refresh all active API read models immediately", () => {
    const api = source("src/lib/api.ts");
    const providers = source("src/components/app/providers.tsx");
    expect(api).toContain('BOARDOPS_DATA_CHANGED_EVENT = "boardops:data-changed"');
    expect(api).toContain("broadcastSuccessfulMutation(path, method)");
    expect(providers).toContain("window.addEventListener(BOARDOPS_DATA_CHANGED_EVENT");
    expect(providers).toContain('root === "api" || root === "apiE"');
    expect(providers).toContain('refetchType: "active"');
  });

  test("active API reads also refresh periodically for changes from another device", () => {
    const hooks = source("src/hooks/use-api-query.ts");
    expect(hooks).toContain("refetchInterval: options?.refetchInterval ?? 15_000");
    expect(hooks).toContain("refetchOnWindowFocus: options?.refetchOnWindowFocus ?? true");
  });

  test("billing publish day is a simple editable audited variable", () => {
    const variables = source("src/app/api/v1/admin/formulas/variables/route.ts");
    expect(variables).toContain('BILLING_PUBLISH_DAY_KEY =');
    expect(variables).toContain('displayName: "Billing Publish Day"');
    expect(variables).toContain("isEditable: true");
    expect(variables).toContain('action: "BILLING_PUBLISH_DAY_UPDATED"');
    expect(variables).toContain("MIN_BILLING_PUBLISH_DAY");
    expect(variables).toContain("MAX_BILLING_PUBLISH_DAY");
  });

  test("published billing remains snapshot based and adjustment-only", () => {
    const billing = source("src/lib/domain/billing.ts");
    expect(billing).toContain("billingSnapshot.create");
    expect(billing).toContain('status: "BILLED"');
    expect(billing).toContain("Generated bills, snapshots, and posted journals are immutable");
    expect(billing).toContain("use reopen plus audited bill adjustments or reversal journals for corrections");
  });
});
